import Link from "next/link";
import { Arrow } from "./shell";
import type { Locale } from "@/lib/site";
import { getResume } from "@/lib/resume";

const dates = {
  en: new Intl.DateTimeFormat("en", { month: "short", year: "numeric", timeZone: "UTC" }),
  es: new Intl.DateTimeFormat("es", { month: "short", year: "numeric", timeZone: "UTC" }),
};

export function FounderStory({ locale }: { locale: Locale }) {
  const es = locale === "es";
  return <section className="mx-auto grid max-w-[1320px] gap-12 px-5 py-16 sm:px-10 sm:py-24 lg:grid-cols-[1fr_1fr] lg:gap-24">
    <div><span className="eyebrow">{es ? "Antes de todo esto" : "Before all this"}</span><h2 className="section-title mt-4">{es ? "El código también" : "The code had"}<br /><span className="text-accent">{es ? "tenía que funcionar" : "to work in"}<br />{es ? "en el almacén." : "the warehouse."}</span></h2><a href="https://www.ycombinator.com/companies/amiloz" className="mt-7 inline-flex items-center gap-3 text-sm font-medium" data-track="project_amiloz">Amiloz · Y Combinator W22<Arrow /></a></div>
    <div><p className="text-lg leading-relaxed">{es ? "En Amiloz desarrollé la primera API, el sitio web, las aplicaciones móviles y las herramientas internas. Después contraté y dirigí al equipo de ingeniería." : "At Amiloz, I built the first API, website, mobile apps, and internal tools. Then I hired and led the engineering team."}</p><p className="mt-5 text-sm leading-[1.85] text-muted">{es ? "La empresa abastecía a tiendas de barrio en México. Nuestro software conectaba pedidos, almacén y entregas. Esa experiencia sigue guiando lo que construyo: entender la operación y hacer que la tecnología la resuelva." : "The company supplied corner stores in Mexico. Our software connected customer orders, warehouses, and deliveries. That experience still shapes what I build: understand the operation, then make the technology work for it."}</p>
      <dl className="mt-9 grid grid-cols-2 gap-x-6 gap-y-8 border-t border-ink/10 pt-7"><div className="flex flex-col"><dt className="order-2 mt-3 text-xs leading-relaxed text-muted">{es ? "Capital levantado por Amiloz" : "Capital raised by Amiloz"}</dt><dd className="order-1 text-[clamp(1.5rem,5vw,2.375rem)] font-medium leading-none tracking-[-.05em]">$3.5M+</dd></div><div className="flex flex-col"><dt className="order-2 mt-3 text-xs leading-relaxed text-muted">{es ? "De clientes empresariales" : "Of business customers"}</dt><dd className="order-1 text-[clamp(1.5rem,5vw,2.375rem)] font-medium leading-none tracking-[-.05em]">{es ? "Cientos" : "Hundreds"}</dd></div><div className="flex flex-col"><dt className="order-2 mt-3 text-xs leading-relaxed text-muted">{es ? "Personas en tecnología, en promedio" : "People in technology, on average"}</dt><dd className="order-1 text-[clamp(1.5rem,5vw,2.375rem)] font-medium leading-none tracking-[-.05em]">~7</dd></div><div className="flex flex-col"><dt className="order-2 mt-3 text-xs leading-relaxed text-muted">Y Combinator</dt><dd className="order-1 text-[clamp(1.5rem,5vw,2.375rem)] font-medium leading-none tracking-[-.05em]">W22</dd></div></dl><Link href={`/${locale}/work/amiloz`} className="mt-9 inline-flex min-h-11 items-center gap-3 text-sm font-medium text-accent">{es ? "El trabajo en Amiloz" : "The work at Amiloz"}<Arrow /></Link>
    </div>
  </section>;
}

export function Experience({ locale }: { locale: Locale }) {
  const es = locale === "es";
  const resume = getResume(locale, "employee");
  const selected = resume.work.filter((work) => ["Nixtla", "Independent", "Consultoría", "Betterfin", "Rappi"].includes(work.name));
  return <section id="experience" className="mx-auto max-w-[1320px] px-5 py-16 sm:px-10 sm:py-24"><div className="grid gap-10 md:grid-cols-[.8fr_1.4fr] md:gap-20"><div><span className="eyebrow">{es ? "Más allá de mis empresas" : "Beyond my own companies"}</span><h2 className="section-title mt-4">{es ? "Buen trabajo." : "Good work."}<br /><span className="text-accent">{es ? "Con buenos equipos." : "With good teams."}</span></h2><Link href={`/${locale}/resume/employee`} className="mt-6 inline-flex items-center gap-3 text-sm font-medium">{es ? "La experiencia completa" : "The full experience"}<Arrow /></Link></div><div>{selected.map((work) => <article key={work.name} className="experience-row grid gap-3 border-t border-ink/10 py-6 sm:grid-cols-[1fr_1.5fr] sm:gap-6"><div><h3 className="text-base font-bold">{["Independent", "Consultoría"].includes(work.name) ? (es ? "Consultoría" : "Independent") : work.name}</h3><p className="mt-1 text-xs text-muted">{work.startDate ? dates[locale].format(new Date(`${work.startDate}-01T00:00:00Z`)) : null}{work.startDate ? (es ? " a " : " to ") : (es ? "Hasta " : "Through ")}{work.endDate ? dates[locale].format(new Date(`${work.endDate}-01T00:00:00Z`)) : (es ? "presente" : "present")}</p></div><div><p className="text-sm font-medium">{work.position}</p><p className="mt-2 text-xs leading-[1.8] text-muted">{["Independent", "Consultoría"].includes(work.name) ? (es ? "Selia, MarketPryce, Ciro y CervezaSiempre para AB InBev." : "Selia, MarketPryce, Ciro, and CervezaSiempre for AB InBev.") : work.summary}</p>{work.name === "Nixtla" && <Link href={`/${locale}/work/nixtla`} className="mt-2 inline-flex min-h-11 items-center gap-2 text-xs font-medium text-accent">{es ? "Leer sobre el trabajo" : "Read about the work"}<Arrow /></Link>}</div></article>)}</div></div></section>;
}

export function About({ locale }: { locale: Locale }) {
  const es = locale === "es";
  return <section id="about" className="mx-auto grid max-w-[1320px] gap-10 px-5 py-16 sm:px-10 sm:py-24 lg:grid-cols-[.8fr_1.4fr] lg:gap-20"><div><span className="eyebrow">{es ? "La persona detrás" : "The person behind the work"}</span><h2 className="section-title mt-4">{es ? "Me gusta hacer" : "I like making"}<br /><span className="text-accent">{es ? "que las cosas existan." : "things exist."}</span></h2></div><div><p className="max-w-[640px] text-xl leading-[1.65] tracking-[-.015em]">{es ? "Empecé a construir software en 2015. He trabajado en logística, finanzas, salud y herramientas para desarrolladores. A veces como fundador. A veces dentro de otro equipo. Siempre cerca del producto." : "I started building software in 2015. I've worked in logistics, finance, healthcare, and developer tools. Sometimes as a founder. Sometimes inside someone else's team. Always close to the product."}</p><p className="mt-6 max-w-[580px] text-sm leading-[1.85] text-muted">{es ? "Me interesa el recorrido completo: entender un problema, diseñar cómo resolverlo, escribir el código y ver qué pasa cuando alguien lo usa. Hoy ese trabajo toma forma en Supervisor y Constructor." : "I'm interested in the whole process: understanding a problem, designing a way through it, writing the code, and seeing what happens when someone uses it. Today, that work takes shape in Supervisor and Constructor."}</p><div className="mt-8 flex flex-wrap gap-2 text-xs">{[es ? "Español e inglés" : "Spanish & English", "YC W22", "Platanus Ventures 2023", "Dev.F 2015"].map((item) => <span key={item} className="rounded-full bg-mist px-4 py-2.5 text-muted">{item}</span>)}</div></div></section>;
}
