import Link from "next/link";
import { notFound } from "next/navigation";
import { Header, Footer, Arrow } from "@/components/shell";
import { CopyButton } from "@/components/copy-button";
import { isLocale, SITE_URL } from "@/lib/site";

export const metadata = { title: "API & MCP" };
export default async function AgentsPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLocale(lang)) notFound();
  const es = lang === "es";
  const api = `${SITE_URL}/api/resume?lang=${lang}&version=founder&format=json`;
  const mcp = JSON.stringify({ mcpServers: { eduardo: { url: `${SITE_URL}/mcp` } } }, null, 2);
  return <><Header locale={lang} path="/agents" /><main id="main" className="mx-auto max-w-[940px] px-5 pb-24 pt-12 sm:px-10 sm:pt-20"><span className="eyebrow">{es ? "Para personas y agentes" : "For people & agents"}</span><h1 className="section-title mt-5">{es ? "El mismo perfil.\nEn el formato que necesitas." : "The same profile.\nIn the format you need."}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-muted">{es ? "Currículums de fundador y de empleado o consultor, en español e inglés. Sin registro ni clave de acceso." : "Founder and employee or consultant resumes, in English and Spanish. No account or API key required."}</p><section className="mt-12"><h2 className="text-xl font-bold">REST API</h2><p className="mt-3 text-sm text-muted">{es ? "Usa lang=en o es, version=founder o employee y format=json o pdf. El JSON incluye todos los detalles de experiencia. Para el PDF, length=short devuelve una página y length=full añade la experiencia detallada." : "Use lang=en or es, version=founder or employee, and format=json or pdf. JSON includes all experience details. For PDFs, length=short returns one page and length=full adds the expanded experience."}</p><pre className="my-5 overflow-x-auto rounded-2xl bg-mist p-5 font-mono text-xs leading-relaxed"><code>{`GET ${api}`}</code></pre><CopyButton value={api} locale={lang} /><Link prefetch={false} href="/api/openapi" download="openapi.json" className="mt-5 inline-flex items-center gap-2 text-sm text-accent">OpenAPI 3.1<Arrow /></Link></section><section className="mt-12 border-t border-ink/10 pt-10"><h2 className="text-xl font-bold">Model Context Protocol</h2><p className="mt-3 text-sm leading-relaxed text-muted">{es ? "Añade el servidor MCP a tu cliente. La herramienta get_resume acepta language, version, format y length. Usa format=pdf y length=full para obtener el PDF detallado. El JSON y los cuatro recursos incluyen todos los detalles de experiencia." : "Add the MCP server to your client. The get_resume tool accepts language, version, format, and length. Use format=pdf with length=full for the detailed PDF. JSON responses and all four resources include the complete experience details."}</p><pre className="my-5 overflow-x-auto rounded-2xl bg-mist p-5 font-mono text-xs leading-relaxed"><code>{mcp}</code></pre><CopyButton value={mcp} locale={lang} /><p className="mt-5 text-xs text-muted">Streamable HTTP · {es ? "Solo lectura" : "Read only"} · <Link prefetch={false} download="llms.txt" href="/llms.txt" className="underline underline-offset-4">llms.txt</Link></p></section></main><Footer locale={lang} /></>;
}
